//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forecast.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
       // public Nullable<int> LocationID { get; set; }
        public int LocationID { get; set; }
        public System.DateTime Period { get; set; }
        public string Wind { get; set; }
        public string Degrees { get; set; }
        public string Temp { get; set; }
        public string Description { get; set; }
        public System.DateTime NextUpdate { get; set; }
        public int WeatherID { get; set; }
        public string Rainfall { get; set; }
        public string Symbol { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
