source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# sass-bootstrap
gem 'bootstrap-sass', '3.2.0.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
# Paginations in the view
gem 'will_paginate', '3.0.7'
gem 'bootstrap-will_paginate', '0.0.10'
# generate fake users
gem 'faker',  '1.4.2'
# responder for api
gem 'responders'
# navigation gem
gem 'geocoder'
# minimal authorization gem
gem 'pundit'
# allows CORS without using workarounds such as JSONP
gem 'rack-cors', :require => 'rack/cors'
# api template builder
gem 'rabl'
# if you are using windows you maybe need this gem
# gem 'tzinfo-data'


group :development do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end
